import React, { useEffect, useState } from 'react';
import { useCareLink } from '../../context/CareLinkContext';
import { Download } from '@/components/icons';

type Collision = { _id: string; hospitalName: string; bedCategory: string; winnerRequestId: string; loserRequestId: string; occurredAt: string };

export const ReportsView: React.FC = () => {
  const { hospitals, emergencies } = useCareLink();
  const [collisions, setCollisions] = useState<Collision[]>([]);
  const [showCollisions, setShowCollisions] = useState(false);
  const [staleThreshold, setStaleThreshold] = useState(10);
  useEffect(() => { fetch('/api/hospital-reservation-collisions', { cache: 'no-store' }).then((response) => response.ok ? response.json() : null).then((result) => { if (result) setCollisions(result.entries ?? []); }).catch(() => {}); fetch('/api/settings', { cache: 'no-store' }).then((response) => response.ok ? response.json() : null).then((result) => { if (result?.settings) setStaleThreshold(result.settings.staleThresholdMinutes); }).catch(() => {}); }, []);
  const allBeds = hospitals.flatMap((hospital) => Object.values(hospital.beds));
  const totalBedsAvailable = allBeds.reduce((sum, bed) => sum + bed.available, 0);
  const totalBedsCapacity = allBeds.reduce((sum, bed) => sum + bed.total, 0);
  const bedOccupancyRate = totalBedsCapacity ? Math.round(((totalBedsCapacity - totalBedsAvailable) / totalBedsCapacity) * 100) : 0;
  const staleCount = hospitals.filter((hospital) => hospital.lastUpdatedMinutesAgo >= staleThreshold).length;
  const accepted = emergencies.filter((item) => ['Assigned', 'Accepted', 'En Route', 'Arrived', 'Completed'].includes(item.status)).length;
  const rejected = emergencies.filter((item) => item.status === 'Rejected' || item.status === 'Timed out').length;
  const etaValues = emergencies.map((item) => item.currentEtaMin).filter((value): value is number => typeof value === 'number');
  const avgEta = etaValues.length ? (etaValues.reduce((sum, value) => sum + value, 0) / etaValues.length).toFixed(1) : '—';
  const exportCsv = () => {
    const rows = [['Hospital', 'General available', 'ICU available', 'Trauma available', 'Ventilators available', 'Freshness minutes'], ...hospitals.map((hospital) => [hospital.name, hospital.beds.general.available, hospital.beds.icu.available, hospital.beds.trauma.available, hospital.beds.ventilators.available, hospital.lastUpdatedMinutesAgo])];
    const csv = rows.map((row) => row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(',')).join('\r\n');
    const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' }));
    const link = document.createElement('a'); link.href = url; link.download = 'carelink-analytics.csv'; link.click(); URL.revokeObjectURL(url);
  };

  return <div className="mx-auto max-w-6xl space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-2xl font-bold tracking-tight text-slate-900">Emergency Health Analytics</h1><p className="mt-0.5 text-xs text-slate-500">Live summaries from shared hospital inventory and request records.</p></div><button type="button" onClick={exportCsv} className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2 text-xs font-semibold text-slate-700"><Download className="h-4 w-4" />Export CSV</button></div>
    <div className="grid grid-cols-2 gap-4 lg:grid-cols-4"><article className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-bold uppercase text-slate-500">Average ETA</p><p className="mt-2 text-3xl font-extrabold text-sky-700">{avgEta}{avgEta !== '—' && 'm'}</p><p className="mt-1 text-[11px] text-slate-500">Across active emergency cases</p></article><article className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-bold uppercase text-slate-500">Bed occupancy</p><p className="mt-2 text-3xl font-extrabold text-slate-900">{bedOccupancyRate}%</p><p className="mt-1 text-[11px] text-slate-500">High load is defined as 80% or more · {totalBedsAvailable} beds free</p></article><article className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-bold uppercase text-slate-500">Collisions defended</p><button type="button" onClick={() => setShowCollisions((value) => !value)} className="mt-2 text-3xl font-extrabold text-sky-700">{collisions.length}</button><p className="mt-1 text-[11px] text-slate-500">Atomic reservation race log · click count to inspect</p></article><article className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-bold uppercase text-slate-500">Stale hospital feeds</p><p className={`mt-2 text-3xl font-extrabold ${staleCount ? 'text-amber-700' : 'text-emerald-700'}`}>{staleCount}</p><p className="mt-1 text-[11px] text-slate-500">Past the configured freshness threshold</p></article></div>
    {showCollisions && <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">Prevented reservation collisions</h2>{collisions.length ? <div className="mt-3 overflow-x-auto"><table className="w-full min-w-[600px] text-left text-xs"><thead className="border-b text-slate-500"><tr><th className="py-2">Hospital / resource</th><th>Winner request</th><th>Returned request</th><th>When</th></tr></thead><tbody className="divide-y">{collisions.map((item) => <tr key={item._id}><td className="py-2">{item.hospitalName} · {item.bedCategory}</td><td>{item.winnerRequestId}</td><td>{item.loserRequestId}</td><td>{new Date(item.occurredAt).toLocaleString()}</td></tr>)}</tbody></table></div> : <p className="mt-3 text-sm text-slate-500">No inventory collision has been recorded yet.</p>}</section>}
    <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">Acceptance vs rejection</h2><p className="mt-1 text-xs text-slate-500">Current emergency case states</p><div className="mt-4 space-y-3"><div><div className="mb-1 flex justify-between text-xs"><span>Accepted / assigned</span><b>{accepted}</b></div><div className="h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-emerald-500" style={{ width: `${emergencies.length ? accepted / emergencies.length * 100 : 0}%` }} /></div></div><div><div className="mb-1 flex justify-between text-xs"><span>Rejected / timed out</span><b>{rejected}</b></div><div className="h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-rose-500" style={{ width: `${emergencies.length ? rejected / emergencies.length * 100 : 0}%` }} /></div></div></div></section><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">Occupancy by hospital</h2><div className="mt-3 space-y-3">{hospitals.map((hospital) => { const total = Object.values(hospital.beds).reduce((sum, bed) => sum + bed.total, 0); const free = Object.values(hospital.beds).reduce((sum, bed) => sum + bed.available, 0); const occupancy = total ? Math.round((total - free) / total * 100) : 0; return <div key={hospital.id}><div className="mb-1 flex justify-between text-xs"><span>{hospital.name}</span><b>{occupancy}%</b></div><div className="h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-sky-600" style={{ width: `${occupancy}%` }} /></div></div>; })}</div></section></div>
    <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">Stale data incidents</h2><p className="mt-1 text-xs text-slate-500">Hospitals currently past the configured {staleThreshold}-minute threshold.</p><div className="mt-3 flex flex-wrap gap-2">{hospitals.filter((hospital) => hospital.lastUpdatedMinutesAgo >= staleThreshold).map((hospital) => <span key={hospital.id} className="rounded-lg bg-amber-50 px-3 py-2 text-xs font-semibold text-amber-900">{hospital.name} · {hospital.lastUpdatedMinutesAgo} min old</span>)}{!staleCount && <span className="text-sm text-slate-500">No stale hospitals.</span>}</div></section>
  </div>;
};
