import { access, mkdir, open, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { HOSPITALS, createRng, type DecisionSample, type SimDay } from "./world.ts";
import { buildReplayEpisodes, modelForecaster, runReplay, type ReplayOutcome } from "./replay.ts";
import type { LogisticModelArtifact } from "../lib/allocation/forecaster.ts";
import type { TrainingStayDurations } from "./features.ts";

const root = fileURLToPath(new URL("../", import.meta.url));
type Dataset = { seed:number; split:string; days:SimDay[]; samples:DecisionSample[]; trainingStayDurations?:TrainingStayDurations };
const BOOTSTRAP_SEED = 20261013;
function args() { const at=process.argv.indexOf("--split"); const split=at<0?undefined:process.argv[at+1]; const nAt=process.argv.indexOf("--episodes"); const episodes=nAt<0?300:Number(process.argv[nAt+1]); if(split!=="validation"&&split!=="test") throw new Error("Pass --split validation or --split test explicitly."); if(!Number.isInteger(episodes)||episodes<1||(split==="test"&&episodes<300)) throw new Error("Test evaluation requires at least 300 episodes."); return {split,episodes}; }
function summarize(results:ReplayOutcome[]) {
 const patients=results.flatMap((r)=>r.patients); const success=patients.filter((p)=>p.minutes!==null); const reasons:Record<string,number>={}; for(const p of patients)if(p.reason)reasons[p.reason]=(reasons[p.reason]??0)+1;
 const times=success.map(p=>p.minutes!).sort((a,b)=>a-b); const urgency1=patients.filter(p=>p.urgency===1); const failU1=urgency1.filter(p=>p.minutes===null).length;
 return {patientCount:patients.length,handoverSuccessOnFirstChoice:patients.filter(p=>p.minutes!==null&&p.firstChoice).length/patients.length,reroutesPerPatient:patients.reduce((s,p)=>s+p.reroutes,0)/patients.length,meanTimeToHandoverMinutes:times.length?times.reduce((s,v)=>s+v,0)/times.length:null,p90TimeToHandoverMinutes:times.length?times[Math.ceil(.9*times.length)-1]:null,unservedCount:patients.length-success.length,unservedByReason:reasons,urgency1FailureRate:urgency1.length?failU1/urgency1.length:0,incompatible_allocations:results.reduce((s,r)=>s+r.incompatible_allocations,0),double_counted_reservations:results.reduce((s,r)=>s+r.double_counted_reservations,0)};
}
function interval(a:ReplayOutcome[],b:ReplayOutcome[],pick:(r:ReplayOutcome)=>number,seed:number){const d=a.map((x,i)=>pick(x)-pick(b[i]));const estimate=d.reduce((s,x)=>s+x,0)/d.length;const rnd=createRng(seed);const boot=Array.from({length:2000},()=>{let s=0;for(let i=0;i<d.length;i++)s+=d[Math.floor(rnd()*d.length)];return s/d.length}).sort((x,y)=>x-y);return {estimate,lower95:boot[49],upper95:boot[1949],resamples:2000,seed};}
function episodeSuccess(r:ReplayOutcome){return r.patients.filter(p=>p.minutes!==null).length/r.patients.length;}
async function main(){const {split,episodes}=args();const evidence=join(root,"evidence");await mkdir(evidence,{recursive:true});const resultPath=join(evidence,split==="test"?"results.json":"validation-results.json");const mdPath=join(evidence,split==="test"?"results.md":"validation-results.md");
 let lock;
 if(split==="test") { lock=await open(join(evidence,".hlth02-test-eval.lock"),"wx").catch(()=>null); if(!lock) throw new Error("Test evaluation has already been started; the one-shot lock exists."); for(const path of [resultPath,mdPath]) await access(path).then(()=>{throw new Error(`Refusing to overwrite existing test result: ${path}`)}).catch((e:unknown)=>{if((e as NodeJS.ErrnoException).code!=="ENOENT")throw e}); }
 try {
  const dataPath=join(root,"data","synthetic",split==="test"?"test.json":"val.json"); const [datasetText,modelText]=await Promise.all([readFile(dataPath,"utf8"),readFile(join(root,"model","model.json"),"utf8")]); const ds=JSON.parse(datasetText) as Dataset; if(ds.split!==split)throw new Error(`Expected ${split} data; found ${ds.split}.`); if(ds.days.some(d=>split==="validation"?(d.day<31||d.day>40):(d.day<41||d.day>50)))throw new Error("Dataset contains days outside requested split.");
  const model=JSON.parse(modelText) as LogisticModelArtifact; const seed=20261020; const eps=buildReplayEpisodes(ds.days,ds.samples,episodes,seed); const mf=modelForecaster(model,ds.days,ds.samples); const baseline=eps.map(ep=>runReplay(ep,({hospital,patient})=>hospital.confirmedFree[patient.resourceType]>0?1:0)); const aware=eps.map(ep=>runReplay(ep,mf));
  const metrics={baseline:summarize(baseline),modelAware:summarize(aware),pairedBootstrap95:{handoverSuccessModelMinusBaseline:interval(aware,baseline,episodeSuccess,BOOTSTRAP_SEED),reroutesPerPatientModelMinusBaseline:interval(aware,baseline,r=>r.patients.reduce((s,p)=>s+p.reroutes,0)/r.patients.length,BOOTSTRAP_SEED+2),meanTimeModelMinusBaseline:interval(aware,baseline,r=>{const x=r.patients.filter(p=>p.minutes!==null).map(p=>p.minutes!);return x.length?x.reduce((s,v)=>s+v,0)/x.length:0},BOOTSTRAP_SEED+1)},seed,episodeCount:episodes,split,days:split==="validation"?[31,40]:[41,50]};
  // Correctly pair reroute differences (per episode); interval above is episode bootstrap.
  metrics.pairedBootstrap95.reroutesPerPatientModelMinusBaseline=interval(aware,baseline,r=>r.patients.reduce((s,p)=>s+p.reroutes,0)/r.patients.length,BOOTSTRAP_SEED+2);
  const worst=eps.map((ep,i)=>({id:ep.id,b:episodeSuccess(baseline[i]),m:episodeSuccess(aware[i]),base:baseline[i],model:aware[i]})).sort((a,b)=>(a.m-a.b)-(b.m-b.b))[0];
  const output={...metrics,caseReview:{episodeId:worst.id,baselineSuccess:worst.b,modelAwareSuccess:worst.m,baseline:worst.base,modelAware:worst.model}};
  if(split==="test"&&(metrics.baseline.incompatible_allocations!==0||metrics.modelAware.incompatible_allocations!==0||metrics.baseline.double_counted_reservations!==0||metrics.modelAware.double_counted_reservations!==0))throw new Error("Replay invariant counters must be zero.");
  await writeFile(resultPath,JSON.stringify(output,null,2)+"\n");
  const md=`# HLTH02 replay evaluation (${split})\n\nEpisodes: ${episodes}; days ${metrics.days[0]}–${metrics.days[1]}; episode seed ${seed}. Both methods replayed identical episode and event draws.\n\n| Metric | Baseline | Model-aware |\n|---|---:|---:|\n| Handover success on first choice | ${(metrics.baseline.handoverSuccessOnFirstChoice*100).toFixed(2)}% | ${(metrics.modelAware.handoverSuccessOnFirstChoice*100).toFixed(2)}% |\n| Reroutes per patient | ${metrics.baseline.reroutesPerPatient.toFixed(3)} | ${metrics.modelAware.reroutesPerPatient.toFixed(3)} |\n| Mean time to handover (min) | ${metrics.baseline.meanTimeToHandoverMinutes?.toFixed(2)??"—"} | ${metrics.modelAware.meanTimeToHandoverMinutes?.toFixed(2)??"—"} |\n| 90th percentile time (min) | ${metrics.baseline.p90TimeToHandoverMinutes??"—"} | ${metrics.modelAware.p90TimeToHandoverMinutes??"—"} |\n| Unserved | ${metrics.baseline.unservedCount} | ${metrics.modelAware.unservedCount} |\n| Urgency-1 failure rate | ${(metrics.baseline.urgency1FailureRate*100).toFixed(2)}% | ${(metrics.modelAware.urgency1FailureRate*100).toFixed(2)}% |\n| Incompatible allocations | ${metrics.baseline.incompatible_allocations} | ${metrics.modelAware.incompatible_allocations} |\n| Double-counted reservations | ${metrics.baseline.double_counted_reservations} | ${metrics.modelAware.double_counted_reservations} |\n\nUnserved reasons: baseline \`${JSON.stringify(metrics.baseline.unservedByReason)}\`; model-aware \`${JSON.stringify(metrics.modelAware.unservedByReason)}\`.\n\nPaired episode-bootstrap 95% CIs for model-aware minus baseline: success ${JSON.stringify(metrics.pairedBootstrap95.handoverSuccessModelMinusBaseline)}; reroutes ${JSON.stringify(metrics.pairedBootstrap95.reroutesPerPatientModelMinusBaseline)}; mean time ${JSON.stringify(metrics.pairedBootstrap95.meanTimeModelMinusBaseline)}.\n\nLog loss is not a fair comparison because the baseline outputs hard 0/1 probabilities.\n`;
  await writeFile(mdPath,md); if(split==="test") { await mkdir(join(evidence,"replay-logs"),{recursive:true}); for(let s=1;s<=6;s++){const ix=(s-1)%episodes; await writeFile(join(evidence,"replay-logs",`S${s}.jsonl`),JSON.stringify({scenario:`S${s}`,episode:eps[ix],baseline:baseline[ix],modelAware:aware[ix]})+"\n");} await writeFile(join(evidence,"limitations.md"), (await readFile(join(evidence,"limitations.md"),"utf8")).replace("## Test-run case review\n\nTo be completed after the replay analysis.",`## Test-run case review\n\nThe one-shot replay review selected ${worst.id}: baseline handover success ${(worst.b*100).toFixed(1)}%, model-aware ${(worst.m*100).toFixed(1)}%. This episode's complete patient outcomes and event logs are preserved in results.json under caseReview. This synthetic case is an observed failure/trade-off, not evidence of real-world performance.`)); }
  console.log(`Wrote ${resultPath}; episodes=${episodes}; baseline first-choice success=${metrics.baseline.handoverSuccessOnFirstChoice.toFixed(3)}; model-aware=${metrics.modelAware.handoverSuccessOnFirstChoice.toFixed(3)}.`);
 } finally { if(lock) await lock.close(); }
}
main().catch((e:unknown)=>{console.error(e);process.exitCode=1});
