import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { GENERATOR, HOSPITALS, RESOURCE_TYPES, simulateWorld } from "./world.ts";
import { splitPeriod } from "./dataset.ts";

const root = fileURLToPath(new URL("../", import.meta.url));
const outputDirectory = join(root, "data", "synthetic");

function calibrationSummary(period: ReturnType<typeof simulateWorld>) {
  const groups = new Map<string, { n: number; gone: number }>();
  // Hold test outcomes out of all generator calibration summaries.
  const calibrationSamples = period.samples.filter((sample) => sample.day <= 40);
  for (const sample of calibrationSamples) {
    if (sample.features.freeNow < sample.unitsNeeded) continue;
    const key = `${sample.hospitalId}/${sample.resourceType}/hour-${sample.features.hour}`;
    const group = groups.get(key) ?? { n: 0, gone: 0 };
    group.n += 1;
    if (sample.label === 0) group.gone += 1;
    groups.set(key, group);
  }
  const populated = [...groups.entries()].filter(([, group]) => group.n >= 20);
  const rates = populated.map(([, group]) => group.gone / group.n);
  const overall = [...groups.values()].reduce((total, group) => ({ n: total.n + group.n, gone: total.gone + group.gone }), { n: 0, gone: 0 });
  const sampleCount = calibrationSamples.length;
  const labelOneCount = calibrationSamples.filter((sample) => sample.label === 1).length;
  const splitSummary = {
    trainDays: [1, 30], validationDays: [31, 40], testDays: [41, 50],
    trainSamples: period.samples.filter((sample) => sample.day <= 30).length,
    validationSamples: period.samples.filter((sample) => sample.day >= 31 && sample.day <= 40).length,
    testSamples: period.samples.filter((sample) => sample.day >= 41).length,
  };
  const labelRate = (labelOneCount / sampleCount) * 100;
  const goneRate = overall.n ? (overall.gone / overall.n) * 100 : 0;
  const minRate = rates.length ? Math.min(...rates) * 100 : 0;
  const maxRate = rates.length ? Math.max(...rates) * 100 : 0;
  const groupCount = populated.length;
  // Keep a tiny guard against a generator accidentally producing no timelines.
  if (period.days.length !== GENERATOR.days || HOSPITALS.length * RESOURCE_TYPES.length !== 8) throw new Error("Generated world does not match the declared scope.");
  return { splitSummary, sampleCount, labelOneCount, labelRate, goneRate, minRate, maxRate, groupCount, groups: populated.map(([key, value]) => ({ key, n: value.n, goneRate: value.gone / value.n })) };
}

function assumptionsMarkdown(seed: number, calibration: ReturnType<typeof calibrationSummary>) {
  const capacities = HOSPITALS.map((hospital) => `| ${hospital.id} | ${hospital.capacity.icu_bed} | ${hospital.capacity.emergency_bed} | ${hospital.capabilities.join(", ") || "none"} | ${hospital.rejectionRate} |`).join("\n");
  const calibratedRange = calibration.goneRate >= 5 && calibration.goneRate <= 40 && calibration.maxRate <= 40
    ? "informative overall and below 40% in populated cells; some low-risk cells are below 5%"
    : "outside the target 5%–40% range; see the table and treat this generator calibration as needing adjustment before Phase 2";
  const groups = calibration.groups.map((group) => `| ${group.key} | ${group.n} | ${(group.goneRate * 100).toFixed(1)}% |`).join("\n");
  return `# Synthetic generator assumptions

Generated by sim/world.ts using TypeScript only. No real patient or hospital data is used.

## Reproduction

- World seed: ${seed} (default ${GENERATOR.baseSeed})
- Random generator: Mulberry32; every stochastic choice uses the seeded stream.
- Generator is frozen at this parameter set for subsequent phases. Do not change it after inspecting test model/evaluation results.
- Run: npm run gen-data.

## World and split

- Minute resolution, 50 consecutive simulated 24-hour days, four hospitals, and two resource types: icu_bed and emergency_bed.
- Train: days 1–30; validation: days 31–40; test: days 41–50. The split is strictly chronological.
- Decision samples: ${GENERATOR.samplesPerDay} per day (random hospital/resource, minute 60–1379, ETA 10–60 minutes, and need 1–${GENERATOR.maxUnitsNeeded} units).
- Samples generated: ${calibration.splitSummary.trainSamples + calibration.splitSummary.validationSamples + calibration.splitSummary.testSamples}; positive label fraction on train+validation only: ${calibration.labelRate.toFixed(1)}%.
- Sample counts: train ${calibration.splitSummary.trainSamples}, validation ${calibration.splitSummary.validationSamples}, test ${calibration.splitSummary.testSamples}.

## Hospital assumptions

| id | ICU units | Emergency units | Capability tags | Confirmation rejection probability |
|---|---:|---:|---|---:|
${capacities}

Per-minute walk-in Poisson rates are ICU/emergency respectively: North ${HOSPITALS[0].walkInRatePerMinute.icu_bed}/${HOSPITALS[0].walkInRatePerMinute.emergency_bed}; East ${HOSPITALS[1].walkInRatePerMinute.icu_bed}/${HOSPITALS[1].walkInRatePerMinute.emergency_bed}; Central ${HOSPITALS[2].walkInRatePerMinute.icu_bed}/${HOSPITALS[2].walkInRatePerMinute.emergency_bed}; West ${HOSPITALS[3].walkInRatePerMinute.icu_bed}/${HOSPITALS[3].walkInRatePerMinute.emergency_bed}. Demand is multiplied by the formula ${GENERATOR.walkInTimePattern} across the day, with maximum base multiplier ${GENERATOR.walkInRateMultiplierMax}.

## Durations, surges, closures, and losses

- Initial occupancy is sampled uniformly from ${GENERATOR.initialOccupancyFraction[0]}–${GENERATOR.initialOccupancyFraction[1]} of capacity, and those synthetic patients are treated as admitted at the simulation start. Stays are log-normal: ICU median ${GENERATOR.icuStayLogNormal.medianMinutes} min, sigma ${GENERATOR.icuStayLogNormal.sigma}; emergency median ${GENERATOR.emergencyStayLogNormal.medianMinutes} min, sigma ${GENERATOR.emergencyStayLogNormal.sigma}. Stays persist across day boundaries.
- Each hospital/resource/day has ${GENERATOR.surgeProbabilityPerHospitalTypeDay} chance of a surge episode; one or occasionally two episodes last ${GENERATOR.surgeDurationMinutes[0]}–${GENERATOR.surgeDurationMinutes[1]} minutes and multiply arrivals by ${GENERATOR.surgeDemandMultiplier}.
- Each hospital/resource/day has ${GENERATOR.closureProbabilityPerHospitalTypeDay} chance of a ${GENERATOR.closureDurationMinutes[0]}–${GENERATOR.closureDurationMinutes[1]} minute closure.
- Each hospital/resource/day has ${GENERATOR.resourceLossProbabilityPerHospitalTypeDay} chance of losing ${GENERATOR.resourceLossUnits} operational unit for the rest of that simulated day. A new day begins with the hospital's declared capacity.
- When demand finds no unit, it is not admitted. Existing stays continue through closures and resource losses; free capacity is clamped at zero.
- Synthetic rejection probabilities are declared per hospital for use by later replay workflows; Phase 1 does not apply them to ground-truth walk-ins.

## Information boundary and labels

- Decision-time sample features use observed availability, current occupancy/capacity, each current patient's elapsed time since admission, prior 30-minute walk-in counts, ETA, hour, synthetic weekday, resource type, and whether the resource is closed now.
- Future walk-ins, future closures, future resource loss, and current-patient total stay lengths are not sample features. The expected-release feature uses elapsed admission times and the completed-stay duration distribution from training days 1–30 only.
- train.json includes only stay durations admitted and released during days 1–30, for constructing that training-period distribution. Validation and test files do not include hidden stay durations. Hidden event logs and future free-unit timelines are stored for replay and independent label verification only.
- Label is 1 exactly when ground-truth free units at minute + etaMin are at least unitsNeeded; arrival minutes beyond the current day are labeled 0 in Phase 1 samples. The independent test recomputes this from the raw timeline.

## Calibration: free now but gone by arrival

This base rate conditions on days 1–40 only and samples where freeNow >= unitsNeeded, grouped by hospital/resource/hour. To avoid treating tiny cells as stable estimates, the populated group range (at least 20 eligible samples per group) is ${calibration.minRate.toFixed(1)}%–${calibration.maxRate.toFixed(1)}% across ${calibration.groupCount} groups, ${calibratedRange}. The weighted overall rate is ${calibration.goneRate.toFixed(1)}%. Low-volume hour cells are excluded from the range; rates vary materially by hospital, resource type, hour, and available slack.

Calibration process note: an earlier exploratory seed was inspected across all splits while adjusting generator rates. The committed dataset uses a fresh default seed after those adjustments, and the final calibration report excludes test labels. The exploratory pass had no trained model or model-evaluation results; this limitation will be carried into the final evidence package.

| hospital/resource/hour | samples with enough units now | gone by arrival |
|---|---:|---:|
${groups}
`;
}

async function main() {
  await mkdir(outputDirectory, { recursive: true });
  const seed = Number(process.env.HLTH02_SEED ?? GENERATOR.baseSeed);
  if (!Number.isInteger(seed) || seed < 0) throw new RangeError("HLTH02_SEED must be a non-negative integer.");
  const period = simulateWorld(seed);
  const splits = splitPeriod(period);
  for (const [name, dataset] of Object.entries(splits)) {
    await writeFile(join(outputDirectory, `${name === "validation" ? "val" : name}.json`), `${JSON.stringify(dataset)}\n`, "utf8");
  }
  const calibration = calibrationSummary(period);
  await writeFile(join(outputDirectory, "assumptions.md"), assumptionsMarkdown(seed, calibration), "utf8");
  console.log(`Generated ${period.days.length} days and ${period.samples.length} samples (seed ${seed}).`);
  console.log(`Samples: train ${calibration.splitSummary.trainSamples}, validation ${calibration.splitSummary.validationSamples}, test ${calibration.splitSummary.testSamples}; positive labels ${calibration.labelRate.toFixed(1)}%.`);
  console.log(`Among train/validation samples with enough units now, ${calibration.goneRate.toFixed(1)}% were gone by ETA; populated hospital/type/hour group range ${calibration.minRate.toFixed(1)}%–${calibration.maxRate.toFixed(1)}% (n=${calibration.groupCount}, at least 20 samples/group).`);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
