'use client';

import { useMemo, useState } from "react";

type Patient={id:string;urgency:1|2|3;requiredResource:"icu_bed"|"emergency_bed";assignedHospital:string|null;etaMin:number;pAvailable:number;probabilityByHospital:Record<string,number>;status:string;reason:string|null;reroutes:number};
type Hospital={id:string;name:string;freeUnits:Record<"icu_bed"|"emergency_bed",number>;closed:boolean};
type Timeline={at:number;patientId:string;hospitalId?:string;event:string;status:string;reason?:string};
type Outcome={patients:Array<{minutes:number|null;reroutes:number}>;incompatible_allocations:number;double_counted_reservations:number};
export type DemoScenario={id:string;name:string;seed:number;description:string;inputs:{day:number;minute:number;patients:unknown[];events:unknown[]};patients:Patient[];hospitals:Hospital[];timeline:Timeline[];expectedOutcomes:{baseline:Outcome;modelAware:Outcome}};
type ModelInfo={type:string;trainingDays:[number,number];testBrier:number;baselineBrier:number};

function score(outcome:Outcome){const patients=outcome.patients;const served=patients.filter(p=>p.minutes!==null).length;return {success:patients.length?served/patients.length:0,reroutes:patients.reduce((s,p)=>s+p.reroutes,0),unserved:patients.length-served};}
const pct=(n:number)=>`${(n*100).toFixed(1)}%`;

export default function ScenarioDemo({scenarios,model}:{scenarios:DemoScenario[];model:ModelInfo}){
 const [selected,setSelected]=useState(scenarios[0]?.id??"S1");const [step,setStep]=useState(0);const [patientId,setPatientId]=useState(scenarios[0]?.patients[0]?.id??"");
 const scenario=scenarios.find(s=>s.id===selected)??scenarios[0];const patient=scenario.patients.find(p=>p.id===patientId)??scenario.patients[0];
 const visibleTimeline=useMemo(()=>scenario.timeline.slice(0,step),[scenario.timeline,step]);const base=score(scenario.expectedOutcomes.baseline);const aware=score(scenario.expectedOutcomes.modelAware);
 function choose(id:string){setSelected(id);setStep(0);const next=scenarios.find(s=>s.id===id);setPatientId(next?.patients[0]?.id??"");}
 return <main className="min-h-screen bg-[#F6F8F9] px-4 py-8 text-[#1B1F23] sm:px-8">
  <div className="mx-auto max-w-7xl space-y-6">
   <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#1E5A8E]">CareLink · Allocation</p><h1 className="mt-2 text-3xl font-bold">Hospital handover simulation</h1><p className="mt-2 max-w-3xl text-sm text-slate-600">Simulation. Synthetic data only; no real patient data is used or written. Select a scenario and step through its saved replay.</p></div><span className="rounded-full border border-[#1E5A8E]/25 bg-white px-3 py-1.5 text-sm font-semibold text-[#1E5A8E]">Simulation</span></header>
   <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-end justify-between gap-4"><div className="min-w-64 flex-1"><label htmlFor="scenario" className="mb-2 block text-sm font-semibold">Scenario</label><select id="scenario" value={scenario.id} onChange={e=>choose(e.target.value)} className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm">{scenarios.map(s=><option key={s.id} value={s.id}>{s.id} · {s.name}</option>)}</select><p className="mt-2 text-sm text-slate-600">{scenario.description} · Day {scenario.inputs.day}, minute {scenario.inputs.minute} · seed {scenario.seed}</p></div><div className="flex gap-2"><button type="button" onClick={()=>setStep(scenario.timeline.length)} className="rounded-lg bg-[#1E5A8E] px-4 py-2.5 text-sm font-semibold text-white hover:bg-[#17476f]">Run</button><button type="button" onClick={()=>setStep(s=>Math.min(s+1,scenario.timeline.length))} className="rounded-lg border border-[#1E5A8E] bg-white px-4 py-2.5 text-sm font-semibold text-[#1E5A8E] hover:bg-blue-50">Step</button><button type="button" onClick={()=>setStep(0)} className="rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">Reset</button></div></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-[#1E5A8E] transition-all" style={{width:`${scenario.timeline.length?step/scenario.timeline.length*100:0}%`}}/></div><p className="mt-1 text-right text-xs text-slate-500">{step} of {scenario.timeline.length} replay events</p></section>
   <div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><section className="space-y-5"><div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-bold">Hospital capacity</h2><label className="text-sm">Chosen patient <select value={patient?.id??""} onChange={e=>setPatientId(e.target.value)} className="ml-2 rounded-md border border-slate-300 px-2 py-1">{scenario.patients.map(p=><option key={p.id} value={p.id}>{p.id} · urgency {p.urgency}</option>)}</select></label></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{scenario.hospitals.map(h=>{const closed=h.closed||visibleTimeline.some(entry=>entry.hospitalId===h.id&&entry.status==="closed");return <article key={h.id} className="rounded-lg border border-slate-200 p-4"><div className="flex justify-between gap-2"><h3 className="font-semibold">{h.name}</h3><span className={`rounded-full px-2 py-0.5 text-xs font-semibold ${closed?"bg-red-50 text-[#C0362C]":"bg-green-50 text-[#2E7D4F]"}`}>{closed?"Closed":"Open"}</span></div><p className="mt-3 text-sm">ICU free <b>{h.freeUnits.icu_bed}</b><span className="mx-2 text-slate-300">|</span>Emergency free <b>{h.freeUnits.emergency_bed}</b></p><p className="mt-2 text-sm text-slate-600">Chosen patient forecast <b className="text-[#1E5A8E]">{patient?pct(patient.probabilityByHospital[h.id]??0):"—"}</b></p></article>})}</div></div>
    <div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="text-lg font-bold">Patients</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Patient</th><th className="px-4 py-3">Urgency</th><th className="px-4 py-3">Requirement</th><th className="px-4 py-3">Hospital / ETA</th><th className="px-4 py-3">P available</th><th className="px-4 py-3">Status / reason</th></tr></thead><tbody>{scenario.patients.map(p=><tr key={p.id} className="border-t border-slate-100"><td className="px-4 py-3 font-semibold">{p.id}</td><td className="px-4 py-3">{p.urgency}</td><td className="px-4 py-3">{p.requiredResource.replace('_',' ')}</td><td className="px-4 py-3">{p.assignedHospital??"—"} · {p.etaMin} min</td><td className="px-4 py-3">{pct(p.pAvailable)}</td><td className="px-4 py-3"><span className={`font-semibold ${p.status==="handed_over"?"text-[#2E7D4F]":"text-[#C0362C]"}`}>{p.status}</span>{p.reason&&<span className="ml-2 text-xs text-slate-600">{p.reason}</span>}</td></tr>)}</tbody></table></div></div>
   </section><section className="space-y-5"><div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">Baseline vs model-aware</h2><div className="mt-4 grid grid-cols-2 gap-3">{[["Baseline",base],["Model-aware",aware]].map(([name,value])=>{const x=value as ReturnType<typeof score>;return <article key={name as string} className="rounded-lg bg-slate-50 p-4"><h3 className="font-semibold">{name as string}</h3><dl className="mt-3 space-y-2 text-sm"><div className="flex justify-between"><dt>Handover success</dt><dd className="font-bold">{pct(x.success)}</dd></div><div className="flex justify-between"><dt>Reroutes</dt><dd className="font-bold">{x.reroutes}</dd></div><div className="flex justify-between"><dt>Unserved</dt><dd className="font-bold">{x.unserved}</dd></div></dl></article>})}</div><p className="mt-3 text-xs text-slate-500">Same scenario inputs and random draws are used for both methods.</p></div>
    <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-lg font-bold">Reservation timeline</h2><span className="text-xs text-slate-500">{visibleTimeline.length} events shown</span></div><ol className="mt-4 max-h-[380px] space-y-3 overflow-auto">{visibleTimeline.length?visibleTimeline.map((entry,i)=><li key={`${entry.patientId}-${i}`} className="flex gap-3 text-sm"><span className="mt-1.5 h-2.5 w-2.5 shrink-0 rounded-full bg-[#C98A1F]"/><span><b>{entry.status}</b> · {entry.event} <span className="text-slate-500">· {entry.patientId} · min {entry.at}</span>{entry.reason&&<span className="block text-[#C0362C]">{entry.reason}</span>}</span></li>):<li className="rounded-lg bg-slate-50 px-3 py-4 text-sm text-slate-500">Press Run or Step to view the event log.</li>}</ol></div>
    <div className="rounded-xl border border-[#1E5A8E]/20 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">Model</h2><p className="mt-2 text-sm">{model.type.replaceAll("_"," ")}</p><p className="mt-1 text-sm text-slate-600">Training days {model.trainingDays[0]}–{model.trainingDays[1]}</p><p className="mt-1 text-sm text-slate-600">Test Brier: model {model.testBrier.toFixed(4)} · baseline {model.baselineBrier.toFixed(4)}</p><p className="mt-3 border-t border-slate-100 pt-3 text-sm font-medium text-[#1E5A8E]">Synthetic data; shows behaviour under declared assumptions</p></div>
   </section></div>
   <footer className="border-t border-slate-200 pt-4 text-xs text-slate-500">Simulation only · No live hospital capacity is read and no real holds are created.</footer>
  </div>
 </main>;
}
