'use client';
import { useEffect, useState } from 'react';

type Preferences = { textSize: 'normal'|'large'|'extra-large'; highContrast: boolean; notificationPreferences: { sos: boolean; requestUpdates: boolean; email: boolean; sound: boolean } };
const defaults: Preferences = { textSize: 'normal', highContrast: false, notificationPreferences: { sos: true, requestUpdates: true, email: true, sound: true } };
export function AccountPreferences() {
  const [value, setValue] = useState(defaults); const [status, setStatus] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { void fetch('/api/me/preferences').then(async response => { if (!response.ok) throw new Error(); const result = await response.json(); setValue(result.preferences); }).catch(() => setStatus('Could not load saved preferences.')).finally(() => setLoading(false)); }, []);
  useEffect(() => { document.documentElement.dataset.textSize = value.textSize; document.documentElement.dataset.highContrast = String(value.highContrast); }, [value.textSize, value.highContrast]);
  const save = async () => { setStatus(''); try { const response = await fetch('/api/me/preferences', { method: 'PATCH', headers: { 'Content-Type':'application/json' }, body: JSON.stringify(value) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Could not save.'); setStatus('Preferences saved.'); } catch (error) { setStatus(error instanceof Error ? error.message : 'Could not save preferences.'); } };
  const toggle = (key: keyof Preferences['notificationPreferences']) => setValue(old => ({ ...old, notificationPreferences: { ...old.notificationPreferences, [key]: !old.notificationPreferences[key] } }));
  if (loading) return <section className="rounded-2xl border border-slate-200 bg-white p-5">Loading account preferences…</section>;
  return <section className="space-y-4 rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-bold">Accessibility and notifications</h2><label className="block text-sm font-semibold">Text size<select value={value.textSize} onChange={event => setValue(old => ({ ...old, textSize: event.target.value as Preferences['textSize'] }))} className="ml-3 rounded-lg border border-slate-300 px-3 py-2"><option value="normal">Normal</option><option value="large">Large</option><option value="extra-large">Extra large</option></select></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={value.highContrast} onChange={event => setValue(old => ({ ...old, highContrast: event.target.checked }))}/>High contrast</label><fieldset className="grid gap-2 sm:grid-cols-2"><legend className="mb-2 text-sm font-semibold">Notification preferences</legend>{([['sos','SOS alerts'],['requestUpdates','Request status updates'],['email','Email notifications'],['sound','Sound']] as const).map(([key,label]) => <label key={key} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={value.notificationPreferences[key]} onChange={() => toggle(key)}/>{label}</label>)}</fieldset><button onClick={() => void save()} className="rounded-lg bg-sky-800 px-4 py-2 font-semibold text-white">Save preferences</button>{status && <p role="status" className="text-sm text-slate-700">{status}</p>}</section>;
}
