import { readFile } from "node:fs/promises";
import { join } from "node:path";

export const metadata = { title: "Hospital recommendation simulation | CareLink", description: "Synthetic recommendation workflow scenarios and model evidence." };

export default async function HospitalDemoPage() {
  const ids = ["H1", "H2", "H3", "H4", "H5", "H6", "H7"];
  const scenarios = await Promise.all(ids.map(async (id) => JSON.parse(await readFile(join(process.cwd(), "data/scenarios", `${id}.json`), "utf8")) as { id: string; name: string; description: string; steps: string[]; outcome: string; reason: string }));
  const metrics = JSON.parse(await readFile(join(process.cwd(), "model/accept-metrics.json"), "utf8")) as { test?: { model: { brierScore: number }; nearestFeasibleBaseline: { brierScore: number } } };
  const model = JSON.parse(await readFile(join(process.cwd(), "model/accept-model.json"), "utf8")) as { modelType: string; trainingPeriod: { days: [number, number] } };
  return <main className="min-h-screen bg-[#F6F8F9] px-4 py-8 text-[#1B1F23] sm:px-6 lg:px-10"><div className="mx-auto max-w-6xl"><p className="inline-flex rounded-full bg-[#C98A1F]/15 px-3 py-1 text-sm font-semibold text-[#80540A]">Simulation / decision support</p><h1 className="mt-3 text-3xl font-bold">Hospital recommendation scenarios</h1><p className="mt-2 max-w-3xl text-sm text-slate-700">Synthetic examples demonstrate the request, response, rerouting, override, and fallback workflow. They are not real patient or hospital records, and recommendations are not guarantees.</p>
    <section aria-labelledby="model-title" className="mt-6 rounded-xl border border-slate-200 bg-white p-5"><h2 id="model-title" className="text-xl font-bold">Acceptance model evidence</h2><dl className="mt-3 grid gap-3 sm:grid-cols-2"><div><dt className="text-xs text-slate-500">Model</dt><dd className="font-semibold">{model.modelType}</dd></div><div><dt className="text-xs text-slate-500">Training days</dt><dd className="font-semibold">{model.trainingPeriod.days.join("–")}</dd></div><div><dt className="text-xs text-slate-500">Test Brier score</dt><dd className="font-semibold">{metrics.test?.model.brierScore.toFixed(4) ?? "Not evaluated"}</dd></div><div><dt className="text-xs text-slate-500">Nearest feasible baseline Brier</dt><dd className="font-semibold">{metrics.test?.nearestFeasibleBaseline.brierScore.toFixed(4) ?? "Not evaluated"}</dd></div></dl><p className="mt-3 text-sm font-semibold">Synthetic data; shows behaviour under declared assumptions.</p></section>
    <section className="mt-7 grid gap-4 md:grid-cols-2" aria-label="Demo scenarios">{scenarios.map((scenario) => <article key={scenario.id} className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex items-start justify-between gap-3"><h2 className="text-lg font-bold">{scenario.id} · {scenario.name}</h2><span className="rounded-full bg-[#1E5A8E]/10 px-2 py-1 text-xs font-semibold text-[#1E5A8E]">Simulation</span></div><p className="mt-2 text-sm text-slate-600">{scenario.description}</p><ol className="mt-4 list-inside list-decimal space-y-1 text-sm">{scenario.steps.map((step) => <li key={step}>{step}</li>)}</ol><p className="mt-3 border-t border-slate-100 pt-3 text-xs text-slate-600">Outcome: <strong>{scenario.outcome}</strong> · reason: <code>{scenario.reason}</code></p></article>)}</section>
    <p className="mt-6 text-xs text-slate-600">The ranking is greedy and is not globally optimal. A driver can override a recommendation; clinical decisions remain with qualified people.</p></div></main>;
}
